FROM nginx:latest

COPY index.html /usr/share/nginx/html/
COPY forum.js /usr/share/nginx/html/
COPY thread.html /usr/share/nginx/html/
COPY thread.js /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
