services:
  frontend:
    build: ./frontend
    container_name: forum-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
      
  api:
    build: ./api
    container_name: forum-api
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:6
    container_name: forum-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: