services:
  api:
    build: ./api
    container_name: forum_api
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGO_URI: "mongodb://database:27017/forum"
    networks:
      - forum_network

  frontend:
    build: ./frontend
    container_name: forum_frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - forum_network

  database:
    image: mongo:6
    container_name: forum_db
    ports:
      - "27017:27017"
    networks:
      - forum_network
    volumes:
      - mongo_data:/data/db
      
  go_app:
    build:
      context: ./docker/
      tags:
        - "demetriussemanko/strata_go_server:latest"
    container_name: go_app
    image: demetriussemanko/strata_go_server:latest
    restart: always
    expose:
      - 8081
    ports:
      - 8081:8081
      
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 go_app

networks:
  forum_network:

volumes:
  mongo_data:
