services:
  frontend:
    #build: ./frontend
    #tags:
    #  - "demetriussemanko/forum-frontend:latest"
    #container_name: forum-frontend
    build:
      context: ./frontend
      tags:
        - "demetriussemanko/forum-frontend:latest"
    container_name: forum-frontend
    image: demetriussemanko/forum-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - api
      
  api:
    #build: ./api
    #tags:
    #  - "demetriussemanko/forum-api:latest"
    build:
      context: ./api
      tags:
        - "demetriussemanko/forum-api:latest"
    container_name: forum-api
    image: demetriussemanko/forum-api:latest
    depends_on:
      - database

  database:
    image: mongo:6
    container_name: forum-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  mongo_data: